rel:
	@cd ive;     make
	@cd nnie;    make
	@cd hirt;    make
clean:
	@cd ive;     make clean
	@cd nnie;    make clean
	@cd hirt;    make clean
cleanall:
	@cd ive;     make clean;   make cleanstream
	@cd nnie;    make clean;   make cleanstream
	@cd hirt;    make clean
